name: CI

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: zotero-chinese/zotero-chinese.github.io
          branch: gh-pages
          folder: dist
          single-commit: true
          token: ${{ secrets.ACCESS_TOKEN }}
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
